---
abstract: 'Catmandu store backend for Dancer::Plugin::RBAC::Credentials'
author:
  - 'Nicolas Franck'
build_requires:
  File::Basename: 0
  File::Spec: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.038
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Auth-RBAC-Credentials-Catmandu
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
recommends:
  Catmandu::Store::DBI: 0.042
requires:
  Catmandu: 0.05
  Dancer: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Dancer-Plugin-Auth-RBAC-Credentials-Catmandu/issues
  homepage: https://github.com/LibreCat/Dancer-Plugin-Auth-RBAC-Credentials-Catmandu
  repository: https://github.com/LibreCat/Dancer-Plugin-Auth-RBAC-Credentials-Catmandu.git
version: 0.01
x_contributors:
  - 'Nicolas Franck <nicolas.franck@ugent.be>'
  - 'Nicolas Franck <njfranck@ca20c521.ugent.be>'
